### ISSUE TITLE
add (history) chart

### ISSUE THREAD

**Issue by greenbigfrog** [greenbigfrog/okcash-ticker#1]
Would be nice to have a chart with the history of the price. It would be ok if the history only gets saved per session (doesn't persist reboot etc.).

**Comment by greenbigfrog** [comment]
Added hacktoberfest label to this issue, since my javascript skills are kinda limited. If you have any questions feel free to ask :smile:

**Comment by ad-dan** [comment]
I will try

**Comment by ad-dan** [comment]
What do you mean by market history ? I am looking through the Bitrex API documentation. It has a few options. 
### /public/getmarketsummary
This option shows market history (High, Low) in the past 24 hours.  It does include the value from previous day.  
So, this option gives 3 numeric values for making a chart.

### /public/getmarkethistory
This option shows recent  trades and the value of the cryptocurrency. The sample data is larger and can be used to make the chart but it would only give you the recent values.  
  
It looks like the extension will only be able to show the history for recent values and go to a max of the last 24 hours. There is no way to obtain any data beyond the last 24 hours from the BITTREX  API.

**Comment by greenbigfrog** [comment]
Might have not been clear enough what I meant. Sorry

In the [code](https://github.com/greenbigfrog/okcash-ticker/blob/master/background.js#L32) I already had a placeholder comment.

the basic idea was to:
- save current price each cycle
- discard data older 24h (or week?)

And display above in a chart

**Comment by ad-dan** [comment]
Understood. Just one more question, How long does each cycle last? I don't have any knowledge about crypto currencies.  
I will start working on this tomorrow since, It's getting close to midnight here. 🌙

**Comment by greenbigfrog** [comment]
With cycle I meant each time the [loop](https://github.com/greenbigfrog/okcash-ticker/blob/master/background.js#L26-L45) executes.
```js
setInterval(function(){
    ...
}, 1000);
```

(Crypto Currencies are something very cool :smile: You should look into them if you're interested (not in trading or something in particular, but more like the code behind it))
